Add windows CI build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -76,69 +76,75 @@ jobs:
   ###########
   # Windows #
   ###########
-  # windows:
-  #   name: Building Windows binary
-  #   runs-on: windows-2019
+  windows:
+    name: Building Windows binary
+    runs-on: windows-2019
 
-  #   strategy:
-  #     matrix:
-  #       arch: [x64]
+    strategy:
+      matrix:
+        arch: [x64]
 
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #       name: Checking out
+    steps:
+      - uses: actions/checkout@v3
+        name: Checking out
 
-  #     - uses: ilammy/msvc-dev-cmd@v1
-  #       name: Configuring build environment
-  #       with: 
-  #         arch: ${{ matrix.arch }}
+      - uses: ilammy/msvc-dev-cmd@v1
+        name: Configuring build environment
+        with: 
+          arch: ${{ matrix.arch }}
 
-  #     - name: Hashing dependency CMake files
-  #       id: dep_cmake_hash
-  #       run: echo "dep_cmake_hash=${{ hashFiles('./deps/**') }}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
+      - name: Hashing dependency CMake files
+        id: dep_cmake_hash
+        run: echo "dep_cmake_hash=${{ hashFiles('./deps/**') }}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
 
-  #     - name: Create Build Environment
-  #       # Some projects don't allow in-source building, so create a separate build directory
-  #       # We'll use this as our working directory for all subsequent commands
-  #       run: |
-  #         cmake -E make_directory ${{github.workspace}}/build
-  #         cmake -E make_directory ${{github.workspace}}/build/dist
-  #         cmake -E make_directory ${{github.workspace}}/deps/build
+      - name: Create Build Environment
+        # Some projects don't allow in-source building, so create a separate build directory
+        # We'll use this as our working directory for all subsequent commands
+        run: |
+          cmake -E make_directory ${{github.workspace}}/build
+          cmake -E make_directory ${{github.workspace}}/build/dist
+          cmake -E make_directory ${{github.workspace}}/deps/build
 
-  #     - uses: actions/cache@v3
-  #       name: Getting dependency cache
-  #       id: cache
-  #       with:
-  #         path: ${{github.workspace}}/deps/build/destdir
-  #         key: ${{ runner.os }}-${{ matrix.arch }}-build-deps-${{ steps.dep_cmake_hash.outputs.dep_cmake_hash }}
+      - uses: actions/cache@v3
+        name: Getting dependency cache
+        id: cache
+        with:
+          path: ${{github.workspace}}/deps/build/destdir
+          key: ${{ runner.os }}-${{ matrix.arch }}-build-deps-${{ steps.dep_cmake_hash.outputs.dep_cmake_hash }}
 
-  #     - name: Build dependencies
-  #       if: ${{ steps.cache.outputs.cache-hit != 'true' }}
-  #       shell: bash
-  #       working-directory: ${{github.workspace}}/deps/build
-  #       run: |
-  #         cmake .. -G "Visual Studio 16 2019"
-  #         cmake --build . 
+      - name: Build dependencies
+        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
+        shell: bash
+        working-directory: ${{github.workspace}}/deps/build
+        run: |
+          cmake .. -G "Visual Studio 16 2019"
+          cmake --build . 
 
-  #     - name: Configure CMake
-  #       # Use a bash shell so we can use the same syntax for environment variable
-  #       # access regardless of the host operating system
-  #       shell: bash
-  #       working-directory: ${{github.workspace}}/build
-  #       # Note the current convention is to use the -S and -B options here to specify source 
-  #       # and build directories, but this is only available with CMake 3.13 and higher.  
-  #       # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
-  #       run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=${{github.workspace}}/deps/build/destdir/usr/local -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/dist -DCATCH_EXTRA_ARGS="--reporter;xml;--out=result-junit.xml"
+      - name: Configure CMake
+        # Use a bash shell so we can use the same syntax for environment variable
+        # access regardless of the host operating system
+        shell: bash
+        working-directory: ${{github.workspace}}/build
+        # Note the current convention is to use the -S and -B options here to specify source 
+        # and build directories, but this is only available with CMake 3.13 and higher.  
+        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
+        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=${{github.workspace}}/deps/build/destdir/usr/local -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/dist -DCATCH_EXTRA_ARGS="--reporter;junit;--out=result-junit.xml"
       
-  #     - name: Build
-  #       working-directory: ${{github.workspace}}/build
-  #       shell: bash
-  #       # Execute the build.  You can specify a specific target with "--target <NAME>"
-  #       run: cmake --build . --config $BUILD_TYPE --target install
+      - name: Build
+        working-directory: ${{github.workspace}}/build
+        shell: bash
+        # Execute the build.  You can specify a specific target with "--target <NAME>"
+        run: cmake --build . --config $BUILD_TYPE --target install
         
-  #     - name: Test
-  #       working-directory: ${{github.workspace}}/build
-  #       shell: bash
-  #       # Execute tests defined by the CMake configuration.  
-  #       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-  #       run: ctest
+      - name: Test
+        working-directory: ${{github.workspace}}/build
+        shell: bash
+        # Execute tests defined by the CMake configuration.  
+        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
+        run: ctest
+
+    - uses: actions/upload-artifact@v3  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+        name: test-results
+        path: ${{github.workspace}}/build/**/result-junit.xml
